name: Feature request
description: Suggest an improvement or new capability.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      render: swift
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context (optional)
